### ISSUE TITLE
Android 12 Permission deny crash

### ISSUE THREAD

**Issue by sushantarora3209** [guolindev/PermissionX#116]
I found this crash on Android 12 (Pixel 3 device). 
Function: showForwardToSettingsDialog(List<String> permissions, String message, String positiveText, String negativeText)

Steps to reproduce it:
Deny the permission 2 (I tried Microphone permission) times and crash occurs as soon as app attempts to display the dialog via: "showForwardToSettingsDialog(List<String> permissions, String message, String positiveText, String negativeText)"
File: ForwardScope.java

Here's the crash logs
java.lang.RuntimeException: Failure delivering result ResultInfo{who=@android:requestPermissions:, request=65537, result=-1, data=Intent { act=android.content.pm.action.REQUEST_PERMISSIONS (has extras) }} to activity {com.gm.guardian.debug/com.gm.guardian.ui.MainActivity}: android.content.res.Resources$NotFoundException: String resource ID #0x0
        at android.app.ActivityThread.deliverResults(ActivityThread.java:5298)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:5337)
        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:54)
        at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2202)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7829)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:982)
     Caused by: android.content.res.Resources$NotFoundException: String resource ID #0x0
        at android.content.res.Resources.getText(Resources.java:444)
        at android.content.res.Resources.getString(Resources.java:537)
        at android.content.Context.getString(Context.java:706)
        at com.permissionx.guolindev.dialog.DefaultDialog.buildPermissionsLayout(DefaultDialog.kt:161)
        at com.permissionx.guolindev.dialog.DefaultDialog.onCreate(DefaultDialog.kt:54)
        at android.app.Dialog.dispatchOnCreate(Dialog.java:424)
        at android.app.Dialog.show(Dialog.java:318)
        at com.permissionx.guolindev.request.PermissionBuilder.showHandlePermissionDialog(PermissionBuilder.kt:311)
        at com.permissionx.guolindev.request.PermissionBuilder.showHandlePermissionDialog(PermissionBuilder.kt:286)
        at com.permissionx.guolindev.request.ForwardScope.showForwardToSettingsDialog(ForwardScope.java:54)

Please dop not hesitate to let me know if I can provide you with any further information.

**Comment by guolindev** [comment]
Thanks. The information is quite enough.

This crash is fixed by this commit: https://github.com/guolindev/PermissionX/commit/b99a1984e33b1c23032930927b3bb906fcd0bba3

You can include the new dependency to resolve the error:

`implementation 'com.guolindev.permissionx:permissionx:1.5.1'`

**Comment by sushantarora3209** [comment]
Thank you very much. It works for 1.5.1
