### ISSUE TITLE
packageName为空？

### ISSUE THREAD

**Issue by DingMr** [guolindev/PermissionX#121]
测试机型：长虹电视   Android 9.0     api 28
申请权限：悬浮框 
```
    <!-- 悬浮窗 -->
    <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW" />
    <uses-permission android:name="android.permission.SYSTEM_OVERLAY_WINDOW" />
```

```
    public void requestDrawOverLays() {
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M && !Settings.canDrawOverlays(this)) {
            SmartToast.info("为了应用正常运行，请勾选上“允许出现在其他应用上");
            try {
                PermissionX.init(this)
                        .permissions(Manifest.permission.SYSTEM_ALERT_WINDOW)
                        .onExplainRequestReason((scope, deniedList) -> {
                            String message = "PermissionX需要您同意以下权限才能正常使用";
                            scope.showRequestReasonDialog(deniedList, message, "Allow", "Deny");
                        })
                        .request((allGranted, grantedList, deniedList) -> {
                            if (allGranted) {
                                SmartToast.success("所有申请的权限都已通过");
                            } else {
                                SmartToast.error("您拒绝了如下权限：$deniedList");
                            }
                        });
            } catch (Exception e) {
                BuglyLog.e(TAG, "e------------>" + e.getMessage());
                SmartToast.error(e.getMessage());

                Intent intent = new Intent(getPackageName());
                intent.setFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
                ComponentName comp = new ComponentName("com.android.tv.settings", "com.android.tv.settings.device.apps.AppManagementActivity");
//                    ComponentName comp = new ComponentName("com.android.tv.settings", "com.android.tv.MainSettings");
                intent.setComponent(comp);
                startActivity(intent);


            }

        }
    }

```

异常：java.lang.NullPointerException: Attempt to read from field 'java.lang.String android.content.pm.PackageItemInfo.packageName' on a null object reference

```
java.lang.NullPointerException: Attempt to read from field 'java.lang.String android.content.pm.PackageItemInfo.packageName' on a null object reference
        at android.os.Parcel.createException(Parcel.java:1956)
        at android.os.Parcel.readException(Parcel.java:1918)
        at android.os.Parcel.readException(Parcel.java:1868)
        at android.app.IActivityManager$Stub$Proxy.startActivity(IActivityManager.java:3755)
        at java.lang.reflect.Method.invoke(Native Method)
        at leakcanary.ServiceWatcher$install$4$2.invoke(ServiceWatcher.kt:85)
        at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
        at $Proxy1.startActivity(Unknown Source)
        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1669)
        at android.app.Activity.startActivityForResult(Activity.java:4586)
        at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:675)
        at androidx.core.app.ActivityCompat.startActivityForResult(ActivityCompat.java:234)
        at androidx.fragment.app.FragmentActivity.startActivityFromFragment(FragmentActivity.java:795)
        at androidx.fragment.app.FragmentActivity$HostCallbacks.onStartActivityFromFragment(FragmentActivity.java:932)
        at androidx.fragment.app.Fragment.startActivityForResult(Fragment.java:1279)
        at androidx.fragment.app.Fragment.startActivityForResult(Fragment.java:1267)
        at com.permissionx.guolindev.request.InvisibleFragment.requestSystemAlertWindowPermissionNow(InvisibleFragment.java:125)
        at com.permissionx.guolindev.request.PermissionBuilder.requestSystemAlertWindowPermissionNow(PermissionBuilder.kt:411)
        at com.permissionx.guolindev.request.RequestSystemAlertWindowPermission.requestAgain(RequestSystemAlertWindowPermission.java:77)
        at com.permissionx.guolindev.request.PermissionBuilder$showHandlePermissionDialog$1.onClick(PermissionBuilder.kt:326)
        at android.view.View.performClick(View.java:6601)
        at android.view.View.performClickInternal(View.java:6578)
        at android.view.View.onKeyUp(View.java:13220)
        at android.widget.TextView.onKeyUp(TextView.java:7768)
        at android.view.KeyEvent.dispatch(KeyEvent.java:2861)
        at android.view.View.dispatchKeyEvent(View.java:12454)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1896)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1896)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1896)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1896)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1896)
        at com.android.internal.policy.DecorView.superDispatchKeyEvent(DecorView.java:428)
        at com.android.internal.policy.PhoneWindow.superDispatchKeyEvent(PhoneWindow.java:1820)
        at android.app.Dialog.dispatchKeyEvent(Dialog.java:811)
        at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:342)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:5182)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5012)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4472)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4525)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4491)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4631)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4499)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4688)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4472)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4525)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4491)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4499)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4472)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4525)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4491)
```

**Comment by guolindev** [comment]
这个应该是系统bug吧，我这边也没有什么特别好的办法，可能在这个长虹电视上就是不能使用Fragment.startActivityForResult这种API？

**Comment by DingMr** [comment]
是有点奇怪，谢谢大哥的解答！

**Comment by guolindev** [comment]
那我就先将问题关闭了。
