### ISSUE TITLE
申请后台定位权限失败,说是没找到。

### ISSUE THREAD

**Issue by lijingjian001** [guolindev/PermissionX#123]
申请后台定位权限。
```
            PermissionX.init(this)
                    .permissions(list_permission)
                    .onExplainRequestReason(new ExplainReasonCallback() {
                        @Override
                        public void onExplainReason(@NonNull ExplainScope scope, @NonNull List<String> deniedList) {
                            scope.showRequestReasonDialog(deniedList, "需要以下权限才能正常使用", "同意", "取消");
                        }
                    })
                    .request(new RequestCallback() {
                        @Override
                        public void onResult(boolean allGranted, @NonNull List<String> grantedList, @NonNull List<String> deniedList) {
                            if (allGranted) {
                                Toast.makeText(getApplicationContext(), "所有申请的权限都已通过", Toast.LENGTH_SHORT).show();
                            } else {
                                Toast.makeText(getApplicationContext(), "您拒绝了以下权限" + deniedList, Toast.LENGTH_SHORT).show();
                            }
                        }
                    });
```
错误代码如下:
```
android.content.pm.PackageManager$NameNotFoundException: android.permission.ACCESS_BACKGROUND_LOCATION
2021-09-22 20:19:01.989 13756-13756/com.baidu.test W/System.err:     at android.app.ApplicationPackageManager.getPermissionInfo(ApplicationPackageManager.java:316)
2021-09-22 20:19:01.989 13756-13756/com.baidu.test W/System.err:     at com.permissionx.guolindev.dialog.DefaultDialog.buildPermissionsLayout(DefaultDialog.kt:132)
2021-09-22 20:19:01.989 13756-13756/com.baidu.test W/System.err:     at com.permissionx.guolindev.dialog.DefaultDialog.onCreate(DefaultDialog.kt:54)
2021-09-22 20:19:01.989 13756-13756/com.baidu.test W/System.err:     at android.app.Dialog.dispatchOnCreate(Dialog.java:407)
2021-09-22 20:19:01.989 13756-13756/com.baidu.test W/System.err:     at android.app.Dialog.show(Dialog.java:302)
2021-09-22 20:19:01.989 13756-13756/com.baidu.test W/System.err:     at com.permissionx.guolindev.request.PermissionBuilder.showHandlePermissionDialog(PermissionBuilder.kt:311)
2021-09-22 20:19:01.989 13756-13756/com.baidu.test W/System.err:     at com.permissionx.guolindev.request.PermissionBuilder.showHandlePermissionDialog(PermissionBuilder.kt:286)
2021-09-22 20:19:01.989 13756-13756/com.baidu.test W/System.err:     at com.permissionx.guolindev.request.ExplainScope.showRequestReasonDialog(ExplainScope.java:54)
2021-09-22 20:19:01.990 13756-13756/com.baidu.test W/System.err:     at com.baidu.test.activity.TracingActivity$10.onExplainReason(TracingActivity.java:989)
2021-09-22 20:19:01.990 13756-13756/com.baidu.test W/System.err:     at com.permissionx.guolindev.request.RequestBackgroundLocationPermission.request(RequestBackgroundLocationPermission.java:67)
2021-09-22 20:19:01.990 13756-13756/com.baidu.test W/System.err:     at com.permissionx.guolindev.request.BaseTask.finish(BaseTask.java:76)
2021-09-22 20:19:01.990 13756-13756/com.baidu.test W/System.err:     at com.permissionx.guolindev.request.RequestNormalPermissions.finish(RequestNormalPermissions.java:31)
2021-09-22 20:19:01.990 13756-13756/com.baidu.test W/System.err:     at com.permissionx.guolindev.request.RequestNormalPermissions.request(RequestNormalPermissions.java:48)
2021-09-22 20:19:01.990 13756-13756/com.baidu.test W/System.err:     at com.permissionx.guolindev.request.RequestChain.runTask(RequestChain.java:55)
2021-09-22 20:19:01.990 13756-13756/com.baidu.test W/System.err:     at com.permissionx.guolindev.request.PermissionBuilder.request(PermissionBuilder.kt:253)
2021-09-22 20:19:01.990 13756-13756/com.baidu.test W/System.err:     at com.baidu.test.activity.TracingActivity.applyPermissons(TracingActivity.java:992)
2021-09-22 20:19:01.990 13756-13756/com.baidu.test W/System.err:     at com.baidu.test.activity.TracingActivity.onCreate(TracingActivity.java:192)
2021-09-22 20:19:01.990 13756-13756/com.baidu.test W/System.err:     at android.app.Activity.performCreate(Activity.java:7232)
2021-09-22 20:19:01.990 13756-13756/com.baidu.test W/System.err:     at android.app.Activity.performCreate(Activity.java:7221)
2021-09-22 20:19:01.990 13756-13756/com.baidu.test W/System.err:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1272)
2021-09-22 20:19:01.990 13756-13756/com.baidu.test W/System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2965)
2021-09-22 20:19:01.990 13756-13756/com.baidu.test W/System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3120)
2021-09-22 20:19:01.990 13756-13756/com.baidu.test W/System.err:     at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
2021-09-22 20:19:01.990 13756-13756/com.baidu.test W/System.err:     at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
2021-09-22 20:19:01.990 13756-13756/com.baidu.test W/System.err:     at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
2021-09-22 20:19:01.990 13756-13756/com.baidu.test W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1840)
```
手机: 小米6
android版本:9
miui: 12 20.6.18 开发版

**Comment by guolindev** [comment]
ACCESS_BACKGROUND_LOCATION是从Android 10开始才有的权限，所以你申请的时候需做一下条件过滤，如果是Android 10以下就不申请这个权限。

**Comment by lijingjian001** [comment]
非常感谢,小米6的android9 可以了。
 但是,华为的手机申请权限的时候直接弹出拒绝信息,没有让用户选择的弹窗。没有报错信息.华为手机型号HLK-AL10,android版本10,emui版本10.1.0。

**Comment by guolindev** [comment]
ACCESS_BACKGROUND_LOCATION是不能单独申请的，你的应用必须要同时申请ACCESS_FINE_LOCATION或者ACCESS_COARSE_LOCATION之后才能行，否则直接申请ACCESS_BACKGROUND_LOCATION就是直接拒绝。

**Comment by lijingjian001** [comment]
那两个权限之前就申请了,是有的。我修改了代码之前申请的这两个权限也再申请一次,貌似还是不可以。我看了应用的定位权限是运行时允许,应该是这个原因。看了其他的issue 看来暂时是没有好的解决办法了。

**Comment by lijingjian001** [comment]
非常感谢。
