### ISSUE TITLE
java.lang.IllegalStateException: FragmentManager is already executing transactions

### ISSUE THREAD

**Issue by weileifrank** [guolindev/PermissionX#135]
在activity使用,代码如下:

```
private fun requestFloatPermission() {
        PermissionX.init(this)
            .permissions(Manifest.permission.SYSTEM_ALERT_WINDOW)
            .onExplainRequestReason { scope, deniedList, beforeRequest ->
                val message = "您的手机没有授予悬浮窗权限，请开启后再试"
                val dialog = CustomDialogFragment(message, deniedList)
                scope.showRequestReasonDialog(dialog)
            }
            .onForwardToSettings { scope, deniedList ->
                val message = "您的手机没有授予悬浮窗权限，请跳到设置页面开启后再试"
                val dialog = CustomDialogFragment(message, deniedList)
                scope.showForwardToSettingsDialog(dialog)
            }
            .request { allGranted, grantedList, deniedList ->
                if (allGranted) {
                    Toast.makeText(this, "所有申请的权限都已通过", Toast.LENGTH_SHORT).show()
                } else {
                    Toast.makeText(this, "您拒绝了如下权限：$deniedList", Toast.LENGTH_SHORT).show()
                }
            }
    }
``` 
- 点击请求->点击开启->跳到悬浮窗设置界面后按返回键
- [ 

https://user-images.githubusercontent.com/22569670/138995112-17163417-e770-4897-b548-3fb764c1c0bb.mp4

]
[src.zip](https://github.com/guolindev/PermissionX/files/7422933/src.zip)

**Comment by GeraltDong** [comment]
看看你的activity是继承的AppCompatActivity吗？

**Comment by weileifrank** [comment]
对的,上面**src.zip**就是测试源代码,你可以看下

**Comment by guolindev** [comment]
你能把崩溃的完整堆栈发出来吗？

**Comment by weileifrank** [comment]
**附上崩溃的堆栈信息如下**
```
AndroidRuntime: FATAL EXCEPTION: main
    Process: com.hiscene.permissontest, PID: 28686
    java.lang.IllegalStateException: FragmentManager is already executing transactions
        at androidx.fragment.app.FragmentManager.ensureExecReady(FragmentManager.java:1931)
        at androidx.fragment.app.FragmentManager.execSingleAction(FragmentManager.java:1967)
        at androidx.fragment.app.BackStackRecord.commitNow(BackStackRecord.java:305)
        at androidx.fragment.app.DialogFragment.showNow(DialogFragment.java:297)
        at com.permissionx.guolindev.request.PermissionBuilder.showHandlePermissionDialog(PermissionBuilder.kt:373)
        at com.permissionx.guolindev.request.ExplainScope.showRequestReasonDialog(ExplainScope.kt:63)
        at com.hiscene.permissontest.MainActivity.requestFloatPermission$lambda-0(MainActivity.kt:39)
        at com.hiscene.permissontest.MainActivity.$r8$lambda$7QFTB2sgIX-vUfzcuhSZ8kMAb3Y(Unknown Source:0)
        at com.hiscene.permissontest.MainActivity$$ExternalSyntheticLambda0.onExplainReason(Unknown Source:0)
        at com.permissionx.guolindev.request.InvisibleFragment.onRequestSystemAlertWindowPermissionResult(InvisibleFragment.kt:343)
        at com.permissionx.guolindev.request.InvisibleFragment.requestSystemAlertWindowLauncher$lambda-2(InvisibleFragment.kt:66)
        at com.permissionx.guolindev.request.InvisibleFragment.$r8$lambda$XCcOAK6buHHj5QnuNVd1utNrASw(Unknown Source:0)
        at com.permissionx.guolindev.request.InvisibleFragment$$ExternalSyntheticLambda2.onActivityResult(Unknown Source:4)
        at androidx.activity.result.ActivityResultRegistry$1.onStateChanged(ActivityResultRegistry.java:148)
        at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:354)
        at androidx.lifecycle.LifecycleRegistry.forwardPass(LifecycleRegistry.java:265)
        at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:307)
        at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:148)
        at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.java:134)
        at androidx.fragment.app.Fragment.performStart(Fragment.java:3026)
        at androidx.fragment.app.FragmentStateManager.start(FragmentStateManager.java:589)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:300)
        at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:112)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1647)
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3128)
        at androidx.fragment.app.FragmentManager.dispatchStart(FragmentManager.java:3079)
        at androidx.fragment.app.FragmentController.dispatchStart(FragmentController.java:262)
        at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:510)
        at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:246)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1447)
        at android.app.Activity.performStart(Activity.java:8237)
        at android.app.ActivityThread.handleStartActivity(ActivityThread.java:4084)
        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:235)
        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:215)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:187)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:105)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2613)
        at android.os.Handler.dispatchMessage(Handler.java:110)
        at android.os.Looper.loop(Looper.java:219)
        at android.app.ActivityThread.main(ActivityThread.java:8668)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)
```

**Comment by SuperKung** [comment]
解决了吗？我这儿也遇到了这个问题

**Comment by LiQinglin007** [comment]
还没解决么？

**Comment by SuperKung** [comment]
@LiQinglin007 我把this改成传入当前的fragment之后就可以了

**Comment by wkbin** [comment]
这是Android 11 的bug

**Comment by XuQK** [comment]
在Android 12上也有问题，虽然不崩了，但返回APP弹窗仍然存在，按道理是应该消失了的。

**Comment by XuQK** [comment]
确定了是PermissionBuilder类中376行调用的showNow方法导致的，我改成show方法，然后延迟个200ms进行下面的button设置，就没问题了，如果不延迟，会直接NPE崩掉。

**Comment by guolindev** [comment]
此问题已修复，升级到1.6.2版本即可。
