### ISSUE TITLE
andorid 8.0 java.lang.IllegalStateException: Only fullscreen activities can request orientation

### ISSUE THREAD

**Issue by tzt1994** [guolindev/PermissionX#153]
![image](https://user-images.githubusercontent.com/15625580/145321589-ec5a512c-7cf1-4f20-afca-7de4b844382f.png)

 
 
Process Name: 'com.zt.iot'
Thread Name: 'main'
Back traces starts.
java.lang.IllegalStateException: Only fullscreen activities can request orientation
	at android.os.Parcel.readException(Parcel.java:1962)
	at android.os.Parcel.readException(Parcel.java:1900)
	at android.app.IActivityManager$Stub$Proxy.setRequestedOrientation(IActivityManager.java:5775)
	at android.app.Activity.setRequestedOrientation(Activity.java:5803)
	at com.permissionx.guolindev.request.PermissionBuilder.lockOrientation(PermissionBuilder.kt:522)
	at com.permissionx.guolindev.request.PermissionBuilder.request(PermissionBuilder.kt:252)
	at com.zt.iot.ui.setting.SettingActivity.bindListener$lambda-7(SettingActivity.kt:73)
	at com.zt.iot.ui.setting.SettingActivity.$r8$lambda$LAAqg5He5UIOIGATYOCv7rDtd50(Unknown Source:0)
	at com.zt.iot.ui.setting.SettingActivity$$ExternalSyntheticLambda2.onClick(Unknown Source:2)
	at com.zt.iot.widget.SettingItemLayout$gestureDetector$1.onSingleTapUp(SettingItemLayout.kt:86)

**Comment by tengdag** [comment]
同样的问题+1

**Comment by guolindev** [comment]
已确认是个bug，会在下个版本中修复

**Comment by LanJD** [comment]
> 已确认是个bug，会在下个版本中修复

郭神你好，麻烦你在maven仓库中把这个1.6.1修复版本提交下

**Comment by guolindev** [comment]
此问题已修复，升级到1.6.2版本即可。
