### ISSUE TITLE
android 12拒绝权限后，崩溃

### ISSUE THREAD

**Issue by BugRui** [guolindev/PermissionX#161]
java.lang.RuntimeException: Failure delivering result ResultInfo{who=@android:requestPermissions:, request=490400196, result=-1, data=Intent { act=android.content.pm.action.REQUEST_PERMISSIONS (has extras) }} to activity {com.syc.slms/com.syc.slms.ui.main.MainActivity}: android.content.res.Resources$NotFoundException: String resource ID #0x0
	at android.app.ActivityThread.deliverResults(ActivityThread.java:5414)
	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5453)
	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:54)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2260)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8090)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)
Caused by: android.content.res.Resources$NotFoundException: String resource ID #0x0
	at android.content.res.Resources.getText(Resources.java:463)
	at android.content.res.MiuiResources.getText(MiuiResources.java:106)
	at android.content.res.Resources.getString(Resources.java:556)
	at android.content.Context.getString(Context.java:715)
	at com.permissionx.guolindev.dialog.DefaultDialog.buildPermissionsLayout(DefaultDialog.kt:113)
	at com.permissionx.guolindev.dialog.DefaultDialog.onCreate(DefaultDialog.kt:35)
	at android.app.Dialog.dispatchOnCreate(Dialog.java:433)
	at android.app.Dialog.show(Dialog.java:327)
	at com.permissionx.guolindev.request.PermissionBuilder.showHandlePermissionDialog(PermissionBuilder.java:285)
	at com.permissionx.guolindev.request.PermissionBuilder.showHandlePermissionDialog(PermissionBuilder.java:265)
	at com.permissionx.guolindev.request.ForwardScope.showForwardToSettingsDialog(ForwardScope.java:54)
	at com.bugrui.permission.PermissionsExtKt.showCustomForwardToSettingsDialog(PermissionsExt.kt:97)
	at com.bugrui.permission.PermissionsExtKt.access$showCustomForwardToSettingsDialog(PermissionsExt.kt:1)
	at com.bugrui.permission.PermissionsExtKt$applyPermissionX$1.onForwardToSettings(PermissionsExt.kt:76)
	at com.permissionx.guolindev.request.InvisibleFragment.onRequestNormalPermissionsResult(InvisibleFragment.java:191)
	at com.permissionx.guolindev.request.InvisibleFragment.onRequestPermissionsResult(InvisibleFragment.java:97)
	at androidx.fragment.app.FragmentManager$11.onActivityResult(FragmentManager.java:2967)
	at androidx.fragment.app.FragmentManager$11.onActivityResult(FragmentManager.java:2939)
	at androidx.activity.result.ActivityResultRegistry.doDispatch(ActivityResultRegistry.java:392)
	at androidx.activity.result.ActivityResultRegistry.dispatchResult(ActivityResultRegistry.java:351)
	at androidx.activity.ComponentActivity.onRequestPermissionsResult(ComponentActivity.java:667)
	at androidx.fragment.app.FragmentActivity.onRequestPermissionsResult(FragmentActivity.java:636)
	at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:8781)
	at android.app.Activity.dispatchActivityResult(Activity.java:8634)
	at android.app.ActivityThread.deliverResults(ActivityThread.java:5407)
	... 13 more

**Comment by tanranran** [comment]
这和[PermissionX](https://github.com/guolindev/PermissionX)
Public 无关吧，看起来像是你代码的错误

**Comment by BugRui** [comment]
> NotFoundException

我更新[PermissionX](https://github.com/guolindev/PermissionX)最新版后就没有这个问题了，

**Comment by guolindev** [comment]
android 12是从Permission 1.6版本才开始支持的，如果是使用的之前的版本，在某些不支持权限下确实会报错。

**Comment by qianmohunchen** [comment]
ok了 升级到1.6.0 然后升级到androidx.appcompat:appcompat:1.3.1 就好了
