### ISSUE TITLE
 java.lang.NoSuchMethodError: No virtual method registerForActivityResult

### ISSUE THREAD

**Issue by shuiZhongBoWen** [guolindev/PermissionX#167]
### 1. error is as follows  :
  java.lang.NoSuchMethodError: No virtual method registerForActivityResult(Landroidx/activity/result/contract/ActivityResultContract;Landroidx/activity/result/ActivityResultCallback;)Landroidx/activity/result/ActivityResultLauncher; in class Lcom/permissionx/guolindev/request/InvisibleFragment; or its super classes (declaration of 'com.permissionx.guolindev.request.InvisibleFragment' appears in /data/app/com.mulancm.yueailiao-XY-TsvHe9xL4yIX_DMQvCg==/base.apk!classes32.dex)
        at com.permissionx.guolindev.request.InvisibleFragment.<init>(InvisibleFragment.kt:51)
        at com.permissionx.guolindev.request.PermissionBuilder.getInvisibleFragment(PermissionBuilder.kt:565)
        at com.permissionx.guolindev.request.PermissionBuilder.requestNow(PermissionBuilder.kt:402)
        at com.permissionx.guolindev.request.RequestNormalPermissions.requestAgain(RequestNormalPermissions.kt:66)
        at com.permissionx.guolindev.request.PermissionBuilder.showHandlePermissionDialog$lambda-0(PermissionBuilder.kt:335)
        at com.permissionx.guolindev.request.PermissionBuilder.lambda$e-dOKWGVVL8KLwv9YCuc4L3KUMI(Unknown Source:0)
        at com.permissionx.guolindev.request.-$$Lambda$PermissionBuilder$e-dOKWGVVL8KLwv9YCuc4L3KUMI.onClick(Unknown Source:11)
        at android.view.View.performClick(View.java:7312)
        at android.view.View.performClickInternal(View.java:7286)
        at android.view.View.access$3600(View.java:838)
        at android.view.View$PerformClick.run(View.java:28242)
        at android.os.Handler.handleCallback(Handler.java:900)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:219)
        at android.app.ActivityThread.main(ActivityThread.java:8668)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)

### 2.  mobile phone brand:
 (1) iQOO 9pro ; (2) OPPOfindX3pro

**Comment by guolindev** [comment]
只有这两个型号的手机会报，其他手机都是好的吗？

**Comment by guolindev** [comment]
从现有堆栈上检查并能发现有出现这种crash的可能，暂时将此问题关闭，等有更多信息提供的话可以重新打开，谢谢。

**Comment by qianmohunchen** [comment]
Caused by: android.content.res.Resources$NotFoundException: String resource ID #0x0
02-15 17:48:22.083 11328 11328 E AndroidRuntime: 	at android.content.res.Resources.getText(Resources.java:489)
02-15 17:48:22.083 11328 11328 E AndroidRuntime: 	at android.content.res.Resources.getString(Resources.java:585)
02-15 17:48:22.083 11328 11328 E AndroidRuntime: 	at android.content.Context.getString(Context.java:713)
02-15 17:48:22.083 11328 11328 E AndroidRuntime: 	at com.permissionx.guolindev.dialog.DefaultDialog.buildPermissionsLayout(DefaultDialog.kt:161)
02-15 17:48:22.083 11328 11328 E AndroidRuntime: 	at com.permissionx.guolindev.dialog.DefaultDialog.onCreate(DefaultDialog.kt:54)
02-15 17:48:22.083 11328 11328 E AndroidRuntime: 	at android.app.Dialog.dispatchOnCreate(Dialog.java:814)

华为 honor50 android12 也出现了

**Comment by leishiyu** [comment]
android.content.res.Resources$NotFoundException: String resource ID #0x0
	at android.app.ActivityThread.deliverResults(ActivityThread.java:5744)
	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5783)
	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:67)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2552)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:223)
	at android.os.Looper.loop(Looper.java:324)
	at android.app.ActivityThread.main(ActivityThread.java:8546)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:582)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1061)
Caused by: android.content.res.Resources$NotFoundException: String resource ID #0x0
	at android.content.res.Resources.getText(Resources.java:503)
	at android.content.res.Resources.getString(Resources.java:596)
	at android.content.Context.getString(Context.java:762)
	at com.permissionx.guolindev.dialog.DefaultDialog.buildPermissionsLayout(DefaultDialog.kt:161)
	at com.permissionx.guolindev.dialog.DefaultDialog.onCreate(DefaultDialog.kt:54)
	at android.app.Dialog.dispatchOnCreate(Dialog.java:538)
	at android.app.Dialog.show(Dialog.java:378)
	at com.permissionx.guolindev.request.PermissionBuilder.showHandlePermissionDialog(PermissionBuilder.kt:311)
	at com.permissionx.guolindev.request.PermissionBuilder.showHandlePermissionDialog(PermissionBuilder.kt:286)
	at com.permissionx.guolindev.request.ForwardScope.showForwardToSettingsDialog(ForwardScope.java:54)
	at com.holderzone.plugin.cornucopia.ui.launch.LaunchActivity.getPermission$lambda$2(LaunchActivity.kt:73)
	at com.holderzone.plugin.cornucopia.ui.launch.LaunchActivity.$r8$lambda$vhqlcz1WgpGJYqx56WBekO3x9WI(Unknown Source:0)
	at com.holderzone.plugin.cornucopia.ui.launch.LaunchActivity$$ExternalSyntheticLambda2.onForwardToSettings(Unknown Source:0)
	at com.permissionx.guolindev.request.InvisibleFragment.onRequestNormalPermissionsResult(InvisibleFragment.java:270)
	at com.permissionx.guolindev.request.InvisibleFragment.onRequestPermissionsResult(InvisibleFragment.java:165)
	at androidx.fragment.app.FragmentManager$11.onActivityResult(FragmentManager.java:2967)
	at androidx.fragment.app.FragmentManager$11.onActivityResult(FragmentManager.java:2939)
	at androidx.activity.result.ActivityResultRegistry.doDispatch(ActivityResultRegistry.java:418)
	at androidx.activity.result.ActivityResultRegistry.dispatchResult(ActivityResultRegistry.java:375)
	at androidx.activity.ComponentActivity.onRequestPermissionsResult(ComponentActivity.java:802)
	at androidx.fragment.app.FragmentActivity.onRequestPermissionsResult(FragmentActivity.java:636)
	at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:9254)
	at android.app.Activity.dispatchActivityResult(Activity.java:9112)
	at android.app.ActivityThread.deliverResults(ActivityThread.java:5737)
	... 13 more

**Comment by IceWaterGuo** [comment]
<img width="1099" alt="image" src="https://github.com/guolindev/PermissionX/assets/30523648/46cbb18a-485a-4376-993f-c0c568be1671">
scope.showRequestReasonDialog(deniedList, msg, "确定");这行代码直接crash了
华为P40 pro 鸿蒙4.0

**Comment by feng88724** [comment]
看起来作者不维护了哦
