### ISSUE TITLE
lateinit property task has not been initialized

### ISSUE THREAD

**Issue by wzr-king** [guolindev/PermissionX#172]
步骤  先拒绝所有权限 然后按照提示去设置权限页面中设置一个权限同意 返回到app 
         在按照提示去设置权限页面开启另外的权限 (这里只进入权限设置页面)  
         然后把刚开启的权限关掉  返回app  崩溃   必现

 测试手机 华为mate30pro

**Comment by guolindev** [comment]
有具体崩溃的堆栈吗？

**Comment by wzr-king** [comment]
版本1.6.0 
    Caused by: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1886930919, result=0, data=null} to activity {com.permissionx.app/com.permissionx.app.MainActivity}: kotlin.UninitializedPropertyAccessException: lateinit property task has not been initialized
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4977)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4289)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4334) 
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52) 
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2073) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:225) 
        at android.app.ActivityThread.main(ActivityThread.java:7563) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:994) 
     Caused by: kotlin.UninitializedPropertyAccessException: lateinit property task has not been initialized
        at com.permissionx.guolindev.request.InvisibleFragment.forwardToSettingsLauncher$lambda-6(InvisibleFragment.kt:94)
        at com.permissionx.guolindev.request.InvisibleFragment.$r8$lambda$Ied-m49zCABuAaqE-xwUtovEl9A(Unknown Source:0)
        at com.permissionx.guolindev.request.InvisibleFragment$$ExternalSyntheticLambda0.onActivityResult(Unknown Source:4)
        at androidx.activity.result.ActivityResultRegistry.doDispatch(ActivityResultRegistry.java:392)
        at androidx.activity.result.ActivityResultRegistry.dispatchResult(ActivityResultRegistry.java:351)
        at androidx.activity.ComponentActivity.onActivityResult(ComponentActivity.java:647)
        at androidx.fragment.app.FragmentActivity.onActivityResult(FragmentActivity.java:164)
        at android.app.Activity.dispatchActivityResult(Activity.java:8249)

版本：1.6.2 
    没有具体堆栈信息 整个app重新启动了

**Comment by guolindev** [comment]
感谢反馈，这个问题在这条commit里已经修复了，所以1.6.2上就不会再crash了 
https://github.com/guolindev/PermissionX/commit/b4611ebe13dc1fb498b370a9ee27d1d352a5d86a
