### ISSUE TITLE
在Android 6.0.1版本上面： FragmentManager is already executing transactions

### ISSUE THREAD

**Issue by zhengxyou** [guolindev/PermissionX#175]
手机型号：Nexus5
Android版本：6.0.1
permissionx版本：1.6.3
场景：在Activity中使用，点击允许权限后报错，权限是授权成功了
 `Caused by: java.lang.IllegalStateException: FragmentManager is already executing transactions
        at androidx.fragment.app.FragmentManager.ensureExecReady(FragmentManager.java:1931)
        at androidx.fragment.app.FragmentManager.execSingleAction(FragmentManager.java:1967)
        at androidx.fragment.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:311)
        at com.permissionx.guolindev.request.PermissionBuilder.removeInvisibleFragment(PermissionBuilder.kt:546)
        at com.permissionx.guolindev.request.PermissionBuilder.endRequest$permissionx_release(PermissionBuilder.kt:592)
        at com.permissionx.guolindev.request.BaseTask.finish(BaseTask.kt:106)
        at com.permissionx.guolindev.request.RequestInstallPackagesPermission.request(RequestInstallPackagesPermission.kt:54)
        at com.permissionx.guolindev.request.BaseTask.finish(BaseTask.kt:54)
        at com.permissionx.guolindev.request.RequestManageExternalStoragePermission.request(RequestManageExternalStoragePermission.kt:54)
        at com.permissionx.guolindev.request.BaseTask.finish(BaseTask.kt:54)
        at com.permissionx.guolindev.request.RequestWriteSettingsPermission.request(RequestWriteSettingsPermission.kt:61)
        at com.permissionx.guolindev.request.BaseTask.finish(BaseTask.kt:54)
        at com.permissionx.guolindev.request.RequestSystemAlertWindowPermission.request(RequestSystemAlertWindowPermission.kt:61)
        at com.permissionx.guolindev.request.BaseTask.finish(BaseTask.kt:54)
        at com.permissionx.guolindev.request.RequestBackgroundLocationPermission.request(RequestBackgroundLocationPermission.kt:62)
        at com.permissionx.guolindev.request.BaseTask.finish(BaseTask.kt:54)
        at com.permissionx.guolindev.request.InvisibleFragment.onRequestNormalPermissionsResult(InvisibleFragment.kt:288)
        at com.permissionx.guolindev.request.InvisibleFragment.requestNormalPermissionLauncher$lambda-0(InvisibleFragment.kt:58)
        at com.permissionx.guolindev.request.InvisibleFragment.$r8$lambda$N68S7qVgI-LTwmw3MPog02_dGbo(InvisibleFragment.kt)
        at com.permissionx.guolindev.request.InvisibleFragment$$ExternalSyntheticLambda6.onActivityResult(D8$$SyntheticClass)
        at androidx.activity.result.ActivityResultRegistry$1.onStateChanged(ActivityResultRegistry.java:148)
        at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:354)
        at androidx.lifecycle.LifecycleRegistry.forwardPass(LifecycleRegistry.java:265)
        at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:307)
        at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:148)
        at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.java:134)
        at androidx.fragment.app.Fragment.performResume(Fragment.java:3044)
        at androidx.fragment.app.FragmentStateManager.resume(FragmentStateManager.java:607)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:306)
        at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:112)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1647)
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3128)
    	at androidx.fragment.app.FragmentManager.dispatchResume(Fragme`

**Comment by guolindev** [comment]
感谢反馈，很重要的线索，已在上面的commit中修复。
