### ISSUE TITLE
奔溃闪退必先（ FragmentManager is already executing transactions）

### ISSUE THREAD

**Issue by 474246820** [guolindev/PermissionX#196]
版本：com.guolindev.permissionx:permissionx:1.6.4

java.lang.IllegalStateException: FragmentManager is already executing transactions
        at androidx.fragment.app.FragmentManager.ensureExecReady(FragmentManager.java:1931)
        at androidx.fragment.app.FragmentManager.execSingleAction(FragmentManager.java:1967)
        at androidx.fragment.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:311)
        at com.permissionx.guolindev.request.PermissionBuilder.getInvisibleFragment(PermissionBuilder.kt:99)
        at com.permissionx.guolindev.request.PermissionBuilder.requestNow(PermissionBuilder.kt:427)
        at com.permissionx.guolindev.request.RequestNormalPermissions.request(RequestNormalPermissions.kt:53)
        at com.permissionx.guolindev.request.RequestChain.runTask$permissionx_release(RequestChain.kt:51)
        at com.permissionx.guolindev.request.PermissionBuilder.startRequest(PermissionBuilder.kt:537)
        at com.permissionx.guolindev.request.PermissionBuilder.request(PermissionBuilder.kt:287)

**Comment by guolindev** [comment]
有调用代码的逻辑吗？只看这个堆栈确实看不出什么问题。最好是能知道你调用申请权限接口的时机，上下文正在做什么事情。

**Comment by loflv** [comment]
我也遇到了。我这边的原因是在fragmentDialog创建时请求了相关权限。修改fragmentDialog创建完成后再请求就可以了

**Comment by guolindev** [comment]
那我暂时将此问题关闭，如果有补充更多信息可以将此问题重新打开，谢谢。

**Comment by 474246820** [comment]
林哥，这个问题是这样的，我在fragmentDialog里边 用activity对象 去PermissionX.init(activity)  就会出现这个问题

**Comment by 474246820** [comment]
> 那我暂时将此问题关闭，如果有补充更多信息可以将此问题重新打开，谢谢。
林哥，这个问题是这样的，我在fragmentDialog里边 用activity对象 去PermissionX.init(activity) 就会出现这个问题

**Comment by 474246820** [comment]
> 那我暂时将此问题关闭，如果有补充更多信息可以将此问题重新打开，谢谢。

很多时候功能是根据后台消息推送过来，当前处于activity 还是 fragment 是不确定的，只能获取到顶层的activity，这样去申请权限，如果在一个fragment的时候 就直接 会有这个奔溃错误
