### ISSUE TITLE
魅蓝note5 拒绝后跳转设置页面，手动设置权限后返回程序崩溃

### ISSUE THREAD

**Issue by duronggang** [guolindev/PermissionX#2]
Caused by: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=131074, result=0, data=null} to activity {com.**/com.ui.activity.backstagesetting.tabmanage.BasicInfoactivity}: kotlin.UninitializedPropertyAccessException: lateinit property permissionBuilder has not been initialized
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4333)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3602)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3680) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2924) 
        at android.app.ActivityThread.-wrap12(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1628) 
        at android.os.Handler.dispatchMessage(Handler.java:110) 
        at android.os.Looper.loop(Looper.java:203) 
        at android.app.ActivityThread.main(ActivityThread.java:6406) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1113) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:974) 
     Caused by: kotlin.UninitializedPropertyAccessException: lateinit property permissionBuilder has not been initialized
        at com.permissionx.guolindev.InvisibleFragment.onActivityResult(InvisibleFragment.kt:168)
        at androidx.fragment.app.FragmentActivity.onActivityResult(FragmentActivity.java:170)

**Comment by guolindev** [comment]
这个问题是每次必现，还是偶发性会出现？ 从日志上次，感觉是跳转到设置页面之后，再回来，permissionBuilder 被系统回收了。

**Comment by duronggang** [comment]
偶发性出现的，应该怎么处理下呢

**Comment by guolindev** [comment]
被回收了肯定是没有办法的，因为我不能擅自再创建一个新的PermissionBuilder实例，新建了也没用，里面保存的授权信息都已经丢失了。这种情况我可以加层判断，如果回收的话，就不进行回调，这样程序就不会崩溃了，但是需要你再请求一次授权，重新走一遍权限请求流程就行了。

**Comment by guolindev** [comment]
已经修正并提交了，你试试看用这个版本还会不会崩溃：

`implementation 'com.permissionx.guolindev:permissionx:1.1.2'`

**Comment by guolindev** [comment]
没有得到更新的反馈，我认为这个问题算是处理掉了，如果后续还有问题，请再重新打开。
