### ISSUE TITLE
I Found crash when request OverlayPermission

### ISSUE THREAD

**Issue by MCT-LIB** [guolindev/PermissionX#216]
java.lang.IllegalStateException: Fragment InvisibleFragment{2e243a3} (8f8afd30-cd6a-41a6-b17f-838a458bd6ce) not attached to a context.
                                                  	at androidx.fragment.app.Fragment.requireContext(Fragment.java:967)
                                                  	at com.permissionx.guolindev.request.InvisibleFragment.onRequestSystemAlertWindowPermissionResult(InvisibleFragment.kt:466)
                                                  	at com.permissionx.guolindev.request.InvisibleFragment.access$onRequestSystemAlertWindowPermissionResult(InvisibleFragment.kt:40)
                                                  	at com.permissionx.guolindev.request.InvisibleFragment$requestSystemAlertWindowLauncher$1$1.invoke(InvisibleFragment.kt:80)
                                                  	at com.permissionx.guolindev.request.InvisibleFragment$requestSystemAlertWindowLauncher$1$1.invoke(InvisibleFragment.kt:79)
                                                  	at com.permissionx.guolindev.request.InvisibleFragment.postForResult$lambda-10(InvisibleFragment.kt:685)
                                                  	at com.permissionx.guolindev.request.InvisibleFragment.$r8$lambda$XljQbwXL656S_Z-v9CKWNCKNlCI(InvisibleFragment.kt)
                                                  	at com.permissionx.guolindev.request.InvisibleFragment$$ExternalSyntheticLambda9.run(D8$$SyntheticClass)
                                                  	at android.os.Handler.handleCallback(Handler.java:754)
                                                  	at android.os.Handler.dispatchMessage(Handler.java:95)
                                                  	at android.os.Looper.loop(Looper.java:165)
                                                  	at android.app.ActivityThread.main(ActivityThread.java:6375)
                                                  	at java.lang.reflect.Method.invoke(Native Method)
                                                  	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:912)
                                                  	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:802)

**Comment by randauto** [comment]
me too I called in Fragment when I ignore permission, It's crashed!
