### ISSUE TITLE
Fragment中使用崩溃

### ISSUE THREAD

**Issue by fuhaodev** [guolindev/PermissionX#224]
版本：1.6.1
手机型号：Pixel 5、小米12SU
现象描述：在Fragment onViewCreated中使用请求权限出现崩溃
崩溃日志：
```
Process Name: 'com.example.demo'
Thread Name: 'main'
Back traces starts.
java.lang.IllegalStateException: FragmentManager is already executing transactions
	at androidx.fragment.app.FragmentManager.ensureExecReady(FragmentManager.java:80)
	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:0)
	at androidx.fragment.app.FragmentManager.handleOnBackPressed(FragmentManager.java:1)
	at androidx.fragment.app.FragmentManager$1.handleOnBackPressed(FragmentManager.java:2)
	at androidx.activity.OnBackPressedDispatcher.b(OnBackPressedDispatcher.java:24)
	at com.qmuiteam.qmui.arch.QMUIFragment.u(QMUIFragment.java:4)
	at com.xsure.xsurenc.ui.device.connect.BleConfigureFragment$$InternalSyntheticLambda$2$340dd378563ba7cc58a1c6e6f98c880db3bb766ebf82481d2ab95733ff4bdb13$2.onResult(BleConfigureFragment.java:0)
	at com.xsure.xsurenc.ui.device.connect.BleConfigureFragment.startScanAfterCheckPermission$lambda-2(BleConfigureFragment.java:0)
	at com.permissionx.guolindev.request.BaseTask.finish(BaseTask.java:0)
	at com.permissionx.guolindev.request.RequestInstallPackagesPermission.request(RequestInstallPackagesPermission.java:0)
	at com.permissionx.guolindev.request.BaseTask.finish(BaseTask.java:0)
	at com.permissionx.guolindev.request.RequestManageExternalStoragePermission.request(RequestManageExternalStoragePermission.java:0)
	at com.permissionx.guolindev.request.BaseTask.finish(BaseTask.java:0)
	at com.permissionx.guolindev.request.RequestWriteSettingsPermission.request(RequestWriteSettingsPermission.java:0)
```
代码：

```
        PermissionX.init(this).permissions(*OBLIGATORY_PERMISSIONS)
            .explainReasonBeforeRequest()
            .onExplainRequestReason { scope, deniedList ->
                scope.showRequestReasonDialog(
                    deniedList,
                    getString(R.string.permission_dialog_message_request_location_reason),
                    getString(R.string.permission_dialog_action_positive),
                    getString(R.string.permission_dialog_action_negative)
                )
            }
            .onForwardToSettings { scope, deniedList ->
                scope.showForwardToSettingsDialog(
                    deniedList,
                    getString(R.string.permission_dialog_message_forward_setting),
                    getString(R.string.common_ok),
                    getString(R.string.common_cancel)
                )
            }
            .request { allGranted, grantedList, deniedList ->
                if (allGranted) {
                    startScan()
                } else {
                    popBackStack()
                }
            }
```

**Comment by Goooler** [comment]
应该是在低端机上比较常见，刚好在同一个 FragmentManger 里面处理 `InvisibleFragment` 和其他 Fragment 的事务，检查状态异常。可以像楼上说的，延迟权限申请的逻辑。

https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:fragment/fragment/src/main/java/androidx/fragment/app/FragmentManager.java;l=1885-1890

https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:fragment/fragment/src/main/java/androidx/fragment/app/FragmentManager.java;l=1858-1861
