### ISSUE TITLE
荣耀手机获取授权失败

### ISSUE THREAD

**Issue by zhangsl1987** [guolindev/PermissionX#237]
2023-04-06 22:00:29.170 28518-28518/com.easyinvoice E/unknown:ReactNative: Exception in native call
    android.content.res.Resources$NotFoundException: String resource ID #0x0
        at android.content.res.Resources.getText(Resources.java:489)
        at android.content.res.Resources.getString(Resources.java:585)
        at android.content.Context.getString(Context.java:713)
        at com.permissionx.guolindev.dialog.DefaultDialog.buildPermissionsLayout(DefaultDialog.kt:113)
        at com.permissionx.guolindev.dialog.DefaultDialog.onCreate(DefaultDialog.kt:35)
        at android.app.Dialog.dispatchOnCreate(Dialog.java:814)
        at android.app.Dialog.show(Dialog.java:454)
        at com.permissionx.guolindev.request.PermissionBuilder.showHandlePermissionDialog(PermissionBuilder.java:285)
        at com.permissionx.guolindev.request.PermissionBuilder.showHandlePermissionDialog(PermissionBuilder.java:265)
        at com.permissionx.guolindev.request.ExplainScope.showRequestReasonDialog(ExplainScope.java:54)
        at com.permissionx.guolindev.request.ExplainScope.showRequestReasonDialog(ExplainScope.java:67)
        at com.easyinvoice.reactnative.sms.SmsModule$1.lambda$run$0(SmsModule.java:80)
        at com.easyinvoice.reactnative.sms.-$$Lambda$SmsModule$1$ItX9GGrn_kV7CMQESv_43x4n5AQ.onExplainReason(Unknown Source:0)
        at com.permissionx.guolindev.request.RequestNormalPermissions.request(RequestNormalPermissions.java:56)
        at com.permissionx.guolindev.request.RequestChain.runTask(RequestChain.java:55)
        at com.permissionx.guolindev.request.PermissionBuilder.request(PermissionBuilder.java:248)
        at com.easyinvoice.reactnative.sms.SmsModule$1.run(SmsModule.java:88)
        at android.os.Handler.handleCallback(Handler.java:955)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
        at android.os.Looper.loopOnce(Looper.java:206)
        at android.os.Looper.loop(Looper.java:296)
        at android.app.ActivityThread.main(ActivityThread.java:8912)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:569)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:976)

**Comment by leitana** [comment]
你解决了吗
我也遇到了，用的PermissionX版本为1.5.0。
手机型号为IQOO Android 12
