### ISSUE TITLE
你好！过神！小米 Redmi 4A 申请权限异常

### ISSUE THREAD

**Issue by z244370114** [guolindev/PermissionX#52]
1.当拒绝权限之后，跳入设置，打开权限，返回到应用时会有开启权限的弹窗提示，此时继续拒绝，则会导致应用崩溃报异常
2.具体看了下原因，因为再次拒绝！grantedPermissions 对象为空，导致界面崩溃
`     Caused by: java.lang.NullPointerException: Attempt to read from field 'java.util.Set com.permissionx.guolindev.request.PermissionBuilder.grantedPermissions' on a null object reference
        at com.permissionx.guolindev.request.InvisibleFragment.onRequestNormalPermissionsResult(InvisibleFragment.java:125)
        at com.permissionx.guolindev.request.InvisibleFragment.onRequestPermissionsResult(InvisibleFragment.java:97)
        at androidx.fragment.app.FragmentActivity.onRequestPermissionsResult(FragmentActivity.java:769)
        at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:6634)
        at android.app.Activity.dispatchActivityResult(Activity.java:6512)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:3734)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:3781) 
        at android.app.ActivityThread.access$1500(ActivityThread.java:153) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1424) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:5523) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629) `

**Comment by guolindev** [comment]
这个错误是由于内存回收引起的空指针问题，我在比较早的版本当中就已经修复这个问题了，所以你可以确认一下你当前使用的PermissionX的版本号。

只要升级成当前最新版的PermissionX，应该就不会再出现空指针异常了。

**Comment by z244370114** [comment]
刚刚升级到 implementation 'com.permissionx.guolindev:permissionx:1.4.0'  还是有报该错误

**Comment by guolindev** [comment]
那你能把最新的错误堆栈发给我吗，我要根据行号定位问题。

**Comment by z244370114** [comment]
抱歉 ！刚刚看错了！没有报错了，但是会有闪屏，应该是弹窗的背景

**Comment by guolindev** [comment]
因为这种是内存被回收了导致的问题，被回收了我也不能做什么额外的处理，能做的就只能是保证不崩而已。被回收的对象我也不能阻止回收，所以这个时候只能让用户再去请求一次权限了。

但这个问题视手机而定，配置高一点的手机一般是不会回收的。

**Comment by z244370114** [comment]
却是如此！谢谢郭神的帮助

**Comment by guolindev** [comment]
OK，那我就把这个问题关闭了。
