### ISSUE TITLE
Caused by: java.lang.IllegalStateException: FragmentManager is already executing transactions

### ISSUE THREAD

**Issue by qhj93** [guolindev/PermissionX#8]
在ViewPager的其中一个fragment中使用PermissionX出现了以下报错：

Caused by: java.lang.IllegalStateException: FragmentManager is already executing transactions
    at androidx.fragment.app.FragmentManagerImpl.ensureExecReady(FragmentManagerImpl.java:1660)
    at androidx.fragment.app.FragmentManagerImpl.execSingleAction(FragmentManagerImpl.java:1692)
    at androidx.fragment.app.BackStackRecord.commitNow(BackStackRecord.java:293)
    at com.permissionx.guolindev.request.PermissionBuilder.getInvisibleFragment(PermissionBuilder.java:275)
    at com.permissionx.guolindev.request.PermissionBuilder.requestNow(PermissionBuilder.java:252)
    at com.permissionx.guolindev.request.RequestNormalPermissions.request(RequestNormalPermissions.java:62)
    at com.permissionx.guolindev.request.RequestChain.runTask(RequestChain.java:55)

**Comment by guolindev** [comment]
已确认是个bug，下个版本中会修复。

**Comment by guolindev** [comment]
1.3.0版本中已支持在Fragment中使用PermissionX，在初始化时传入Frament的实例即可，就不会再出现此异常。

如果还有问题，请重新打开。

**Comment by qhj93** [comment]
@guolindev 郭神，看到你早上推的文章后马上就去更新了，更新到1.3.0后就不会触发这个bug了。另外，想要复现这个bug只需要在fragment的onCreate、onResume等生命周期方法中调用PermissionX就会出现这个报错，你那边没有复现是不是因为你在调用PermissionX的时候fragment已经创建完成了，比如在onClick里面调用就不会出现这个报错。
