### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by 330676687** [guolindev/PermissionX#92]
```
Thread Name: 'main'
Back traces starts.
android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.content.pm.action.REQUEST_PERMISSIONS pkg=com.lbe.security.miui (has extras) }
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2069)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1868)
	at android.app.Activity.startActivityForResult(Activity.java:6154)
	at android.app.Activity.requestPermissions(Activity.java:5341)
	at androidx.core.app.ActivityCompat.requestPermissions(ActivityCompat.java:502)
	at androidx.fragment.app.FragmentActivity.requestPermissionsFromFragment(FragmentActivity.java:860)
	at androidx.fragment.app.FragmentActivity$HostCallbacks.onRequestPermissionsFromFragment(FragmentActivity.java:947)
	at androidx.fragment.app.Fragment.requestPermissions(Fragment.java:1389)
	at com.permissionx.guolindev.request.InvisibleFragment.requestNow(InvisibleFragment.java:79)
	at com.permissionx.guolindev.request.PermissionBuilder.requestNow(PermissionBuilder.java:371)
	at com.permissionx.guolindev.request.RequestNormalPermissions.request(RequestNormalPermissions.java:62)
	at com.permissionx.guolindev.request.RequestChain.runTask(RequestChain.java:55)
	at com.permissionx.guolindev.request.PermissionBuilder.request(PermissionBuilder.java:248)
	at com.z.tzrl.ui.splash.SplashFragment$onLazyAfterView$2.invokeSuspend(SplashFragment.java:65)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(BaseContinuationImpl.java:33)
	at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTaskKt.java:234)
	at kotlinx.coroutines.internal.DispatchedContinuation.resumeUndispatchedWith(DispatchedContinuation.java:266)
	at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTaskKt.java:166)
	at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.java:398)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.java:432)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default(CancellableContinuationImpl.java:421)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeUndispatched(CancellableContinuationImpl.java:519)
	at kotlinx.coroutines.android.HandlerContext$scheduleResumeAfterDelay$$inlined$Runnable$1.run(HandlerContext.java:19)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:236)
	at android.app.ActivityThread.main(ActivityThread.java:8095)
	at java.lang.reflect.Method.invoke(Method.java)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:620)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1011)
Back traces ends.
```

线上看到的崩溃，设备Redmi M2006J10C  Android11

**Comment by healthyxth** [comment]
`android.content.ActivityNotFoundException

No Activity found to handle Intent { act=android.content.pm.action.REQUEST_PERMISSIONS pkg=com.google.android.packageinstaller (has extras) }`

**Comment by healthyxth** [comment]
我这边也出现了类似的问题，设备是索尼ZX1（G8342），Android 9,level 28

```
  android.content.ActivityNotFoundException
  No Activity found to handle Intent { act=android.content.pm.action.REQUEST_PERMISSIONS pkg=com.google.android.packageinstaller (has extras) }
  android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2014)
  android.app.Instrumentation.execStartActivity(Instrumentation.java:1814)
  android.app.Activity.startActivityForResult(Activity.java:5275)
  android.app.Activity.requestPermissions(Activity.java:4481)
  androidx.core.app.a.a(ActivityCompat.java:502)
  androidx.activity.ComponentActivity$2.a(ComponentActivity.java:187)
  androidx.activity.result.c$2.a(ActivityResultRegistry.java:224)
  androidx.activity.result.b.a(ActivityResultLauncher.java:47)
  androidx.fragment.app.FragmentManager.a(FragmentManager.java:3040)
  androidx.fragment.app.Fragment.requestPermissions(Fragment.java:1561)
  com.permissionx.guolindev.request.InvisibleFragment.a(InvisibleFragment.java:79)
  com.permissionx.guolindev.request.e.a(PermissionBuilder.java:371)
  com.permissionx.guolindev.request.h.d(RequestNormalPermissions.java:62)
  com.permissionx.guolindev.request.g.a(RequestChain.java:55)
  com.permissionx.guolindev.request.e.a(PermissionBuilder.java:248)
```

**Comment by yz1309** [comment]
` 
09-06  11:44:44.021 24517 24517 E AndroidRuntime: java.lang.RuntimeException:  Failure delivering result ResultInfo{who=@android:requestPermissions:,  request=65537, result=-1, data=Intent {  act=android.content.pm.action.REQUEST_PERMISSIONS (has extras) }} to  activity  {hc.ng.mt/com.app.apply.ApplyActivity}:  java.lang.NullPointerException: Attempt to read from field  'java.util.Set l.n.a.c.d.h' on a null object reference
--
8909-06 11:44:44.021 24517 24517 E AndroidRuntime: 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5042)
9009-06 11:44:44.021 24517 24517 E AndroidRuntime: 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5086)
9109-06 11:44:44.021 24517 24517 E AndroidRuntime: 	at android.app.ActivityThread.-wrap20(Unknown Source:0)
9209-06 11:44:44.021 24517 24517 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2071)
9309-06 11:44:44.021 24517 24517 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:109)
9409-06 11:44:44.021 24517 24517 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:166)
9509-06 11:44:44.021 24517 24517 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7555)
9609-06 11:44:44.021 24517 24517 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
9709-06  11:44:44.021 24517 24517 E AndroidRuntime: 	at  com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:469)
9809-06 11:44:44.021 24517 24517 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:963)
9909-06  11:44:44.021 24517 24517 E AndroidRuntime: Caused by:  java.lang.NullPointerException: Attempt to read from field  'java.util.Set l.n.a.c.d.h' on a null object reference
10009-06  11:44:44.021 24517 24517 E AndroidRuntime: 	at  com.permissionx.guolindev.request.InvisibleFragment.onRequestPermissionsResult(:1)
10109-06  11:44:44.021 24517 24517 E AndroidRuntime: 	at  androidx.fragment.app.FragmentActivity.onRequestPermissionsResult(Unknown  Source:68)
10209-06 11:44:44.021 24517 24517 E AndroidRuntime: 	at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:7786)
10309-06 11:44:44.021 24517 24517 E AndroidRuntime: 	at android.app.Activity.dispatchActivityResult(Activity.java:7637)
10409-06 11:44:44.021 24517 24517 E AndroidRuntime: 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5038)
 `
